# Generated by Django 4.2.1 on 2023-05-28 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_or_phone",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '1234567890'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.EmailValidator(
                        message="Please enter a valid email address."
                    ),
                ],
                verbose_name="Email or Phone",
            ),
        ),
    ]
