# Generated by Django 4.2.1 on 2023-05-28 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_customuser_email_or_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_or_phone",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a valid email address or phone number.",
                        regex="^\\+?1?\\d{9,15}$|^([\\w.%+-]+)@([\\w-]+\\.)+([\\w]{2,})$",
                    )
                ],
                verbose_name="Email or Phone",
            ),
        ),
    ]
